/**
 * AUTO-GENERATED by scripts/spec-hygiene/41-generate-skeletons.mjs
 * Source:    spec/contract.json (generator: 40-generate-contract-json.mjs)
 * Generated: 2026-04-29
 * DO NOT EDIT — re-run the generator after spec changes.
 */


import type { AxiosInstance, AxiosResponse } from 'axios';

/** Standard API envelope per spec/04-database-conventions/06-rest-api-format/. */
export interface ApiEnvelope<T> {
  Status: { Code: number; Message: string };
  Attributes: Record<string, unknown>;
  Results: T;
  Navigation?: Record<string, unknown>;
  Errors?: Array<{ Code: string; Message: string }>;
  MethodsStack?: string[];
}

export interface WorkFlowyApi {
  /** EP-BOARD-GET — GET `items/{id}/board` (spec/31-app/06-endpoints/07-board-view.md:19) */
  boardGet(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-BOARD-MOVE — POST `items/{id}/board/move` (spec/31-app/06-endpoints/07-board-view.md:31) */
  boardMove(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-BULK-COMPLETE — POST `items/bulk/complete` (spec/31-app/06-endpoints/12-multi-select.md:45) */
  bulkComplete(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-BULK-DELETE — POST `items/bulk/delete` (spec/31-app/06-endpoints/12-multi-select.md:35) */
  bulkDelete(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-BULK-MOVE — POST `items/bulk/move` (spec/31-app/06-endpoints/12-multi-select.md:24) */
  bulkMove(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-BULK-TAGS — POST `items/bulk/tags` (spec/31-app/06-endpoints/12-multi-select.md:55) */
  bulkTags(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-COMPLETE — POST `items/{id}/complete` (spec/31-app/06-endpoints/06-item-context-menu.md:34) */
  itemsComplete(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-CREATE — POST `items` (spec/31-app/06-endpoints/01-information-model.md:48) */
  itemsCreate(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-DELETE — DELETE `items/{id}` (spec/31-app/06-endpoints/01-information-model.md:90) */
  itemsDelete(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-DUPLICATE — POST `items/{id}/duplicate` (spec/31-app/06-endpoints/06-item-context-menu.md:21) */
  itemsDuplicate(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-GET — GET `items/{id}` (spec/31-app/06-endpoints/01-information-model.md:36) */
  itemsGet(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-LIST — GET `items` (spec/31-app/06-endpoints/01-information-model.md:24) */
  itemsList(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-MOVE — POST `items/{id}/move` (spec/31-app/06-endpoints/01-information-model.md:75) */
  itemsMove(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-ROOT — GET `items/root` (spec/31-app/06-endpoints/01-information-model.md:101) */
  itemsRoot(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-TAGS — POST `items/{id}/tags` (spec/31-app/06-endpoints/06-item-context-menu.md:57) */
  itemsTags(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-TURN-INTO — POST `items/{id}/turn-into` (spec/31-app/06-endpoints/06-item-context-menu.md:45) */
  itemsTurnInto(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ITEMS-UPDATE — PUT `items/{id}` (spec/31-app/06-endpoints/01-information-model.md:64) */
  itemsUpdate(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ME — GET `me` (spec/31-app/06-endpoints/02-personas.md:18) */
  me(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-MIRRORS-CREATE — POST `items/{id}/mirror` (spec/31-app/06-endpoints/09-mirrors.md:20) */
  mirrorsCreate(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-MIRRORS-DELETE — DELETE `mirrors/{mirrorId}` (spec/31-app/06-endpoints/09-mirrors.md:41) */
  mirrorsDelete(mirrorId: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-MIRRORS-DETACH — POST `items/{id}/mirror-detach` (spec/31-app/06-endpoints/09b-mirror-peer-group.md:32) */
  mirrorsDetach(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-MIRRORS-GROUP-GET — GET `items/{id}/mirror-group` (spec/31-app/06-endpoints/09b-mirror-peer-group.md:22) */
  mirrorsGroupGet(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-MIRRORS-LIST — GET `items/{id}/mirrors` (spec/31-app/06-endpoints/09-mirrors.md:32) */
  mirrorsList(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-REAPER-RUN — POST `admin/trash/reaper/run` (spec/31-app/06-endpoints/11b-trash-reaper.md:22) */
  reaperRun(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-REAPER-RUNS-LIST — GET `admin/trash/reaper/runs` (spec/31-app/06-endpoints/11b-trash-reaper.md:37) */
  reaperRunsList(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ROLES-ASSIGN — POST `roles` (spec/31-app/06-endpoints/15-roles-and-permissions.md:32) */
  rolesAssign(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ROLES-LIST — GET `roles` (spec/31-app/06-endpoints/15-roles-and-permissions.md:22) */
  rolesList(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-ROLES-REVOKE — DELETE `roles/{assignmentId}` (spec/31-app/06-endpoints/15-roles-and-permissions.md:42) */
  rolesRevoke(assignmentId: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SEARCH-QUERY — GET `search` (spec/31-app/06-endpoints/15b-search.md:18) */
  searchQuery(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SHARES-INVITE — POST `items/{id}/shares` (spec/31-app/06-endpoints/08-share-dialog.md:31) */
  sharesInvite(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SHARES-LIST — GET `items/{id}/shares` (spec/31-app/06-endpoints/08-share-dialog.md:22) */
  sharesList(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SHARES-PUBLIC — POST `items/{id}/shares/public` (spec/31-app/06-endpoints/08-share-dialog.md:61) */
  sharesPublic(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SHARES-REVOKE — DELETE `items/{id}/shares/{shareId}` (spec/31-app/06-endpoints/08-share-dialog.md:52) */
  sharesRevoke(id: string, shareId: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SHARES-UPDATE — PUT `items/{id}/shares/{shareId}` (spec/31-app/06-endpoints/08-share-dialog.md:42) */
  sharesUpdate(id: string, shareId: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SYNC-ACK — POST `sync/ack` (spec/31-app/06-endpoints/14-concurrency-and-sync.md:53) */
  syncAck(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SYNC-POLL — GET `sync/poll` (spec/31-app/06-endpoints/14-concurrency-and-sync.md:42) */
  syncPoll(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SYNC-REPLAY — POST `sync/replay` (spec/31-app/06-endpoints/14b-sync-replay.md:19) */
  syncReplay(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-SYNC-STREAM — GET `sync/stream` (spec/31-app/06-endpoints/14-concurrency-and-sync.md:22) */
  syncStream(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TEMPLATES-APPLY — POST `templates/{id}/apply` (spec/31-app/06-endpoints/13-templates.md:52) */
  templatesApply(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TEMPLATES-CREATE — POST `templates` (spec/31-app/06-endpoints/13-templates.md:32) */
  templatesCreate(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TEMPLATES-DELETE — DELETE `templates/{id}` (spec/31-app/06-endpoints/13-templates.md:63) */
  templatesDelete(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TEMPLATES-GET — GET `templates/{id}` (spec/31-app/06-endpoints/13-templates.md:43) */
  templatesGet(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TEMPLATES-LIST — GET `templates` (spec/31-app/06-endpoints/13-templates.md:22) */
  templatesList(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TRASH-LIST — GET `trash` (spec/31-app/06-endpoints/11-trash-view.md:21) */
  trashList(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TRASH-PURGE-ALL — DELETE `trash` (spec/31-app/06-endpoints/11-trash-view.md:52) */
  trashPurgeAll(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TRASH-PURGE-ONE — DELETE `trash/{id}` (spec/31-app/06-endpoints/11-trash-view.md:43) */
  trashPurgeOne(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-TRASH-RESTORE — POST `trash/{id}/restore` (spec/31-app/06-endpoints/11-trash-view.md:32) */
  trashRestore(id: string): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
  /** EP-VIEWS-TODAY — GET `views/today` (spec/31-app/06-endpoints/10-today-view.md:18) */
  viewsToday(): Promise<AxiosResponse<ApiEnvelope<unknown>>>;
}

export function createWorkFlowyApi(http: AxiosInstance): WorkFlowyApi {
  const ns = '/wp-json/workflowy/v1';
  return {
    boardGet: (id: string) => http.get(`${ns}/items/${id}/board`),
    boardMove: (id: string) => http.post(`${ns}/items/${id}/board/move`, undefined),
    bulkComplete: () => http.post(`${ns}/items/bulk/complete`, undefined),
    bulkDelete: () => http.post(`${ns}/items/bulk/delete`, undefined),
    bulkMove: () => http.post(`${ns}/items/bulk/move`, undefined),
    bulkTags: () => http.post(`${ns}/items/bulk/tags`, undefined),
    itemsComplete: (id: string) => http.post(`${ns}/items/${id}/complete`, undefined),
    itemsCreate: () => http.post(`${ns}/items`, undefined),
    itemsDelete: (id: string) => http.delete(`${ns}/items/${id}`),
    itemsDuplicate: (id: string) => http.post(`${ns}/items/${id}/duplicate`, undefined),
    itemsGet: (id: string) => http.get(`${ns}/items/${id}`),
    itemsList: () => http.get(`${ns}/items`),
    itemsMove: (id: string) => http.post(`${ns}/items/${id}/move`, undefined),
    itemsRoot: () => http.get(`${ns}/items/root`),
    itemsTags: (id: string) => http.post(`${ns}/items/${id}/tags`, undefined),
    itemsTurnInto: (id: string) => http.post(`${ns}/items/${id}/turn-into`, undefined),
    itemsUpdate: (id: string) => http.put(`${ns}/items/${id}`, undefined),
    me: () => http.get(`${ns}/me`),
    mirrorsCreate: (id: string) => http.post(`${ns}/items/${id}/mirror`, undefined),
    mirrorsDelete: (mirrorId: string) => http.delete(`${ns}/mirrors/${mirrorId}`),
    mirrorsDetach: (id: string) => http.post(`${ns}/items/${id}/mirror-detach`, undefined),
    mirrorsGroupGet: (id: string) => http.get(`${ns}/items/${id}/mirror-group`),
    mirrorsList: (id: string) => http.get(`${ns}/items/${id}/mirrors`),
    reaperRun: () => http.post(`${ns}/admin/trash/reaper/run`, undefined),
    reaperRunsList: () => http.get(`${ns}/admin/trash/reaper/runs`),
    rolesAssign: () => http.post(`${ns}/roles`, undefined),
    rolesList: () => http.get(`${ns}/roles`),
    rolesRevoke: (assignmentId: string) => http.delete(`${ns}/roles/${assignmentId}`),
    searchQuery: () => http.get(`${ns}/search`),
    sharesInvite: (id: string) => http.post(`${ns}/items/${id}/shares`, undefined),
    sharesList: (id: string) => http.get(`${ns}/items/${id}/shares`),
    sharesPublic: (id: string) => http.post(`${ns}/items/${id}/shares/public`, undefined),
    sharesRevoke: (id: string, shareId: string) => http.delete(`${ns}/items/${id}/shares/${shareId}`),
    sharesUpdate: (id: string, shareId: string) => http.put(`${ns}/items/${id}/shares/${shareId}`, undefined),
    syncAck: () => http.post(`${ns}/sync/ack`, undefined),
    syncPoll: () => http.get(`${ns}/sync/poll`),
    syncReplay: () => http.post(`${ns}/sync/replay`, undefined),
    syncStream: () => http.get(`${ns}/sync/stream`),
    templatesApply: (id: string) => http.post(`${ns}/templates/${id}/apply`, undefined),
    templatesCreate: () => http.post(`${ns}/templates`, undefined),
    templatesDelete: (id: string) => http.delete(`${ns}/templates/${id}`),
    templatesGet: (id: string) => http.get(`${ns}/templates/${id}`),
    templatesList: () => http.get(`${ns}/templates`),
    trashList: () => http.get(`${ns}/trash`),
    trashPurgeAll: () => http.delete(`${ns}/trash`),
    trashPurgeOne: (id: string) => http.delete(`${ns}/trash/${id}`),
    trashRestore: (id: string) => http.post(`${ns}/trash/${id}/restore`, undefined),
    viewsToday: () => http.get(`${ns}/views/today`),
  };
}