/**
 * AUTO-GENERATED by scripts/spec-hygiene/41-generate-skeletons.mjs
 * Source:    spec/contract.json (generator: 40-generate-contract-json.mjs)
 * Generated: 2026-04-30
 * DO NOT EDIT — re-run the generator after spec changes.
 */


// {@see spec/20-enums-index.md:61}
export const BackupStrategyType = {
  Full: 'Full',
  Incremental: 'Incremental',
  Differential: 'Differential',
} as const;
export type BackupStrategyType = typeof BackupStrategyType[keyof typeof BackupStrategyType];

// {@see spec/20-enums-index.md:67}
export const CapabilityType = {
  ManageOptions: 'ManageOptions',
  EditPosts: 'EditPosts',
  UploadFiles: 'UploadFiles',
} as const;
export type CapabilityType = typeof CapabilityType[keyof typeof CapabilityType];

// {@see spec/20-enums-index.md:93}
export const ECast001 = {
  CAST_TYPE_ASSERTION_FAILED: 'CAST_TYPE_ASSERTION_FAILED',
} as const;
export type ECast001 = typeof ECast001[keyof typeof ECast001];

// {@see spec/20-enums-index.md:94}
export const ECast002 = {
  CAST_SLICE_ELEMENT_FAILED: 'CAST_SLICE_ELEMENT_FAILED',
} as const;
export type ECast002 = typeof ECast002[keyof typeof ECast002];

// {@see spec/20-enums-index.md:53}
export const ErrorCategoryType = {
  Connection: 'Connection',
  RemoteSite: 'RemoteSite',
  Resource: 'Resource',
  Validation: 'Validation',
  Server: 'Server',
  WpRemote: 'WpRemote',
  Scheduler: 'Scheduler',
  Delegated: 'Delegated',
  Frontend: 'Frontend',
} as const;
export type ErrorCategoryType = typeof ErrorCategoryType[keyof typeof ErrorCategoryType];

// {@see spec/20-enums-index.md:107}
export const HeaderType = {
  Authorization: 'Authorization',
} as const;
export type HeaderType = typeof HeaderType[keyof typeof HeaderType];

// {@see spec/20-enums-index.md:52}
export const HttpMethodType = {
  Get: 'Get',
  Post: 'Post',
  Put: 'Put',
  Patch: 'Patch',
  Delete: 'Delete',
  Options: 'Options',
  Head: 'Head',
} as const;
export type HttpMethodType = typeof HttpMethodType[keyof typeof HttpMethodType];

// {@see spec/20-enums-index.md:76}
export const LogColumnType = {
  Id: 'Id',
  CreatedAt: 'CreatedAt',
  UpdatedAt: 'UpdatedAt',
  Status: 'Status',
  Sequence: 'Sequence',
} as const;
export type LogColumnType = typeof LogColumnType[keyof typeof LogColumnType];

// {@see spec/20-enums-index.md:51}
export const LogLevelType = {
  Trace: 'Trace',
  Debug: 'Debug',
  Info: 'Info',
  Warn: 'Warn',
  Error: 'Error',
  Fatal: 'Fatal',
} as const;
export type LogLevelType = typeof LogLevelType[keyof typeof LogLevelType];

// {@see spec/20-enums-index.md:77}
export const MigrationStatusType = {
  Pending: 'Pending',
  Running: 'Running',
  Completed: 'Completed',
  Failed: 'Failed',
  Rolledback: 'Rolledback',
} as const;
export type MigrationStatusType = typeof MigrationStatusType[keyof typeof MigrationStatusType];

// {@see spec/20-enums-index.md:68}
export const PluginConfigType = {
  Version: 'Version',
  Slug: 'Slug',
  MainFile: 'MainFile',
  TextDomain: 'TextDomain',
} as const;
export type PluginConfigType = typeof PluginConfigType[keyof typeof PluginConfigType];

// {@see spec/20-enums-index.md:69}
export const PostStatusType = {
  Publish: 'Publish',
  Draft: 'Draft',
  Pending: 'Pending',
  Trash: 'Trash',
  Future: 'Future',
  Private: 'Private',
} as const;
export type PostStatusType = typeof PostStatusType[keyof typeof PostStatusType];

// {@see spec/20-enums-index.md:109}
export const ResponseKeyType = {
  Status: 'Status',
  Data: 'Data',
  Errors: 'Errors',
  Attributes: 'Attributes',
} as const;
export type ResponseKeyType = typeof ResponseKeyType[keyof typeof ResponseKeyType];

// {@see spec/20-enums-index.md:110}
export const ResponseMessageType = {
  Success: 'success',
  Failed: 'failed',
  Pending: 'pending',
} as const;
export type ResponseMessageType = typeof ResponseMessageType[keyof typeof ResponseMessageType];

// {@see spec/20-enums-index.md:86}
export const SharePermissionType = {
  View: 'View',
  Comment: 'Comment',
  Edit: 'Edit',
  Owner: 'Owner',
} as const;
export type SharePermissionType = typeof SharePermissionType[keyof typeof SharePermissionType];

// {@see spec/20-enums-index.md:59}
export const SnapshotScopeType = {
  All: 'All',
  PerTable: 'PerTable',
  SingleDb: 'SingleDb',
} as const;
export type SnapshotScopeType = typeof SnapshotScopeType[keyof typeof SnapshotScopeType];

// {@see spec/20-enums-index.md:60}
export const SnapshotTriggerType = {
  Manual: 'Manual',
  Scheduled: 'Scheduled',
  Api: 'Api',
  WebhookExternal: 'WebhookExternal',
  Recovery: 'Recovery',
} as const;
export type SnapshotTriggerType = typeof SnapshotTriggerType[keyof typeof SnapshotTriggerType];

// {@see spec/20-enums-index.md:84}
export const SortDirectionType = {
  Asc: 'Asc',
  Desc: 'Desc',
  Manual: 'Manual',
} as const;
export type SortDirectionType = typeof SortDirectionType[keyof typeof SortDirectionType];

// {@see spec/20-enums-index.md:50}
export const StatusType = {
  Success: 'Success',
  Failed: 'Failed',
  Pending: 'Pending',
  Skipped: 'Skipped',
} as const;
export type StatusType = typeof StatusType[keyof typeof StatusType];

// {@see spec/20-enums-index.md:75}
export const TableType = {
  Transactions: 'Transactions',
  AgentSites: 'AgentSites',
  SnapshotProgress: 'SnapshotProgress',
  PluginSettings: 'PluginSettings',
} as const;
export type TableType = typeof TableType[keyof typeof TableType];

// {@see spec/20-enums-index.md:87}
export const TrashRetentionType = {
  Days30: 'Days30',
  Permanent: 'Permanent',
} as const;
export type TrashRetentionType = typeof TrashRetentionType[keyof typeof TrashRetentionType];

// {@see spec/20-enums-index.md:85}
export const ZoomLevelType = {
  Root: 'Root',
  Single: 'Single',
  Filtered: 'Filtered',
} as const;
export type ZoomLevelType = typeof ZoomLevelType[keyof typeof ZoomLevelType];
