<?php
/**
 * AUTO-GENERATED by scripts/spec-hygiene/41-generate-skeletons.mjs
 * Source:    spec/contract.json (generator: 40-generate-contract-json.mjs)
 * Generated: 2026-04-29
 * DO NOT EDIT — re-run the generator after spec changes.
 *
 * Reference skeleton ONLY. While spec-only mode is active these files
 * live under spec/15-wp-plugin-how-to/skeletons/ as normative samples.
 */

declare(strict_types=1);
namespace WorkFlowy\Generated;


/** {@see spec/20-enums-index.md:61} */
enum BackupStrategyType: string {
    case Full = 'Full';
    case Incremental = 'Incremental';
    case Differential = 'Differential';
}

/** {@see spec/20-enums-index.md:67} */
enum CapabilityType: string {
    case ManageOptions = 'ManageOptions';
    case EditPosts = 'EditPosts';
    case UploadFiles = 'UploadFiles';
}

/** {@see spec/20-enums-index.md:93} */
enum ECast001: string {
    case CAST_TYPE_ASSERTION_FAILED = 'CAST_TYPE_ASSERTION_FAILED';
}

/** {@see spec/20-enums-index.md:94} */
enum ECast002: string {
    case CAST_SLICE_ELEMENT_FAILED = 'CAST_SLICE_ELEMENT_FAILED';
}

/** {@see spec/20-enums-index.md:53} */
enum ErrorCategoryType: string {
    case Connection = 'Connection';
    case RemoteSite = 'RemoteSite';
    case Resource = 'Resource';
    case Validation = 'Validation';
    case Server = 'Server';
    case WpRemote = 'WpRemote';
    case Scheduler = 'Scheduler';
    case Delegated = 'Delegated';
    case Frontend = 'Frontend';
}

/** {@see spec/20-enums-index.md:107} */
enum HeaderType: string {
    case Authorization = 'Authorization';
}

/** {@see spec/20-enums-index.md:52} */
enum HttpMethodType: string {
    case Get = 'Get';
    case Post = 'Post';
    case Put = 'Put';
    case Patch = 'Patch';
    case Delete = 'Delete';
    case Options = 'Options';
    case Head = 'Head';
}

/** {@see spec/20-enums-index.md:76} */
enum LogColumnType: string {
    case Id = 'Id';
    case CreatedAt = 'CreatedAt';
    case UpdatedAt = 'UpdatedAt';
    case Status = 'Status';
    case Sequence = 'Sequence';
}

/** {@see spec/20-enums-index.md:51} */
enum LogLevelType: string {
    case Trace = 'Trace';
    case Debug = 'Debug';
    case Info = 'Info';
    case Warn = 'Warn';
    case Error = 'Error';
    case Fatal = 'Fatal';
}

/** {@see spec/20-enums-index.md:77} */
enum MigrationStatusType: string {
    case Pending = 'Pending';
    case Running = 'Running';
    case Completed = 'Completed';
    case Failed = 'Failed';
    case Rolledback = 'Rolledback';
}

/** {@see spec/20-enums-index.md:68} */
enum PluginConfigType: string {
    case Version = 'Version';
    case Slug = 'Slug';
    case MainFile = 'MainFile';
    case TextDomain = 'TextDomain';
}

/** {@see spec/20-enums-index.md:69} */
enum PostStatusType: string {
    case Publish = 'Publish';
    case Draft = 'Draft';
    case Pending = 'Pending';
    case Trash = 'Trash';
    case Future = 'Future';
    case Private = 'Private';
}

/** {@see spec/20-enums-index.md:109} */
enum ResponseKeyType: string {
    case Status = 'Status';
    case Data = 'Data';
    case Errors = 'Errors';
    case Attributes = 'Attributes';
}

/** {@see spec/20-enums-index.md:110} */
enum ResponseMessageType: string {
    case Success = 'success';
    case Failed = 'failed';
    case Pending = 'pending';
}

/** {@see spec/20-enums-index.md:86} */
enum SharePermissionType: string {
    case View = 'View';
    case Comment = 'Comment';
    case Edit = 'Edit';
    case Owner = 'Owner';
}

/** {@see spec/20-enums-index.md:59} */
enum SnapshotScopeType: string {
    case All = 'All';
    case PerTable = 'PerTable';
    case SingleDb = 'SingleDb';
}

/** {@see spec/20-enums-index.md:60} */
enum SnapshotTriggerType: string {
    case Manual = 'Manual';
    case Scheduled = 'Scheduled';
    case Api = 'Api';
    case WebhookExternal = 'WebhookExternal';
    case Recovery = 'Recovery';
}

/** {@see spec/20-enums-index.md:84} */
enum SortDirectionType: string {
    case Asc = 'Asc';
    case Desc = 'Desc';
    case Manual = 'Manual';
}

/** {@see spec/20-enums-index.md:50} */
enum StatusType: string {
    case Success = 'Success';
    case Failed = 'Failed';
    case Pending = 'Pending';
    case Skipped = 'Skipped';
}

/** {@see spec/20-enums-index.md:75} */
enum TableType: string {
    case Transactions = 'Transactions';
    case AgentSites = 'AgentSites';
    case SnapshotProgress = 'SnapshotProgress';
    case PluginSettings = 'PluginSettings';
}

/** {@see spec/20-enums-index.md:87} */
enum TrashRetentionType: string {
    case Days30 = 'Days30';
    case Permanent = 'Permanent';
}

/** {@see spec/20-enums-index.md:85} */
enum ZoomLevelType: string {
    case Root = 'Root';
    case Single = 'Single';
    case Filtered = 'Filtered';
}
