<?php
/**
 * AUTO-GENERATED by scripts/spec-hygiene/41-generate-skeletons.mjs
 * Source:    spec/contract.json (generator: 40-generate-contract-json.mjs)
 * Generated: 2026-04-29
 * DO NOT EDIT — re-run the generator after spec changes.
 *
 * Reference skeleton ONLY. While spec-only mode is active these files
 * live under spec/15-wp-plugin-how-to/skeletons/ as normative samples.
 */

declare(strict_types=1);
namespace WorkFlowy\Generated;


/**
 * Wire under WordPress 'rest_api_init' action:
 *   add_action('rest_api_init', [WorkFlowy\Generated\RestRoutes::class, 'register']);
 */
final class RestRoutes {
    public const NAMESPACE = 'workflowy/v1';

    public static function register(): void {
        // EP-BOARD-GET — defined spec/31-app/06-endpoints/07-board-view.md:19
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/board', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_board_get'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-BOARD-MOVE — defined spec/31-app/06-endpoints/07-board-view.md:31
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/board/move', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_board_move'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-BULK-COMPLETE — defined spec/31-app/06-endpoints/12-multi-select.md:45
        register_rest_route(self::NAMESPACE, 'items/bulk/complete', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_bulk_complete'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-BULK-DELETE — defined spec/31-app/06-endpoints/12-multi-select.md:35
        register_rest_route(self::NAMESPACE, 'items/bulk/delete', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_bulk_delete'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-BULK-MOVE — defined spec/31-app/06-endpoints/12-multi-select.md:24
        register_rest_route(self::NAMESPACE, 'items/bulk/move', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_bulk_move'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-BULK-TAGS — defined spec/31-app/06-endpoints/12-multi-select.md:55
        register_rest_route(self::NAMESPACE, 'items/bulk/tags', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_bulk_tags'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-COMPLETE — defined spec/31-app/06-endpoints/06-item-context-menu.md:34
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/complete', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_items_complete'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-CREATE — defined spec/31-app/06-endpoints/01-information-model.md:48
        register_rest_route(self::NAMESPACE, 'items', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_items_create'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-DELETE — defined spec/31-app/06-endpoints/01-information-model.md:90
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)', [
            'methods'             => 'DELETE',
            'callback'            => [self::class, 'handle_items_delete'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-DUPLICATE — defined spec/31-app/06-endpoints/06-item-context-menu.md:21
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/duplicate', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_items_duplicate'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-GET — defined spec/31-app/06-endpoints/01-information-model.md:36
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_items_get'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-LIST — defined spec/31-app/06-endpoints/01-information-model.md:24
        register_rest_route(self::NAMESPACE, 'items', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_items_list'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-MOVE — defined spec/31-app/06-endpoints/01-information-model.md:75
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/move', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_items_move'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-ROOT — defined spec/31-app/06-endpoints/01-information-model.md:101
        register_rest_route(self::NAMESPACE, 'items/root', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_items_root'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-TAGS — defined spec/31-app/06-endpoints/06-item-context-menu.md:57
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/tags', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_items_tags'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-TURN-INTO — defined spec/31-app/06-endpoints/06-item-context-menu.md:45
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/turn-into', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_items_turn_into'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ITEMS-UPDATE — defined spec/31-app/06-endpoints/01-information-model.md:64
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)', [
            'methods'             => 'PUT',
            'callback'            => [self::class, 'handle_items_update'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ME — defined spec/31-app/06-endpoints/02-personas.md:18
        register_rest_route(self::NAMESPACE, 'me', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_me'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-MIRRORS-CREATE — defined spec/31-app/06-endpoints/09-mirrors.md:20
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/mirror', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_mirrors_create'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-MIRRORS-DELETE — defined spec/31-app/06-endpoints/09-mirrors.md:41
        register_rest_route(self::NAMESPACE, 'mirrors/(?P<mirrorId>[\\w-]+)', [
            'methods'             => 'DELETE',
            'callback'            => [self::class, 'handle_mirrors_delete'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-MIRRORS-DETACH — defined spec/31-app/06-endpoints/09b-mirror-peer-group.md:32
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/mirror-detach', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_mirrors_detach'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-MIRRORS-GROUP-GET — defined spec/31-app/06-endpoints/09b-mirror-peer-group.md:22
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/mirror-group', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_mirrors_group_get'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-MIRRORS-LIST — defined spec/31-app/06-endpoints/09-mirrors.md:32
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/mirrors', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_mirrors_list'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-REAPER-RUN — defined spec/31-app/06-endpoints/11b-trash-reaper.md:22
        register_rest_route(self::NAMESPACE, 'admin/trash/reaper/run', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_reaper_run'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-REAPER-RUNS-LIST — defined spec/31-app/06-endpoints/11b-trash-reaper.md:37
        register_rest_route(self::NAMESPACE, 'admin/trash/reaper/runs', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_reaper_runs_list'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ROLES-ASSIGN — defined spec/31-app/06-endpoints/15-roles-and-permissions.md:32
        register_rest_route(self::NAMESPACE, 'roles', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_roles_assign'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ROLES-LIST — defined spec/31-app/06-endpoints/15-roles-and-permissions.md:22
        register_rest_route(self::NAMESPACE, 'roles', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_roles_list'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-ROLES-REVOKE — defined spec/31-app/06-endpoints/15-roles-and-permissions.md:42
        register_rest_route(self::NAMESPACE, 'roles/(?P<assignmentId>[\\w-]+)', [
            'methods'             => 'DELETE',
            'callback'            => [self::class, 'handle_roles_revoke'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SEARCH-QUERY — defined spec/31-app/06-endpoints/15b-search.md:18
        register_rest_route(self::NAMESPACE, 'search', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_search_query'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SHARES-INVITE — defined spec/31-app/06-endpoints/08-share-dialog.md:31
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/shares', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_shares_invite'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SHARES-LIST — defined spec/31-app/06-endpoints/08-share-dialog.md:22
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/shares', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_shares_list'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SHARES-PUBLIC — defined spec/31-app/06-endpoints/08-share-dialog.md:61
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/shares/public', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_shares_public'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SHARES-REVOKE — defined spec/31-app/06-endpoints/08-share-dialog.md:52
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/shares/(?P<shareId>[\\w-]+)', [
            'methods'             => 'DELETE',
            'callback'            => [self::class, 'handle_shares_revoke'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SHARES-UPDATE — defined spec/31-app/06-endpoints/08-share-dialog.md:42
        register_rest_route(self::NAMESPACE, 'items/(?P<id>[\\w-]+)/shares/(?P<shareId>[\\w-]+)', [
            'methods'             => 'PUT',
            'callback'            => [self::class, 'handle_shares_update'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SYNC-ACK — defined spec/31-app/06-endpoints/14-concurrency-and-sync.md:53
        register_rest_route(self::NAMESPACE, 'sync/ack', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_sync_ack'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SYNC-POLL — defined spec/31-app/06-endpoints/14-concurrency-and-sync.md:42
        register_rest_route(self::NAMESPACE, 'sync/poll', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_sync_poll'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SYNC-REPLAY — defined spec/31-app/06-endpoints/14b-sync-replay.md:19
        register_rest_route(self::NAMESPACE, 'sync/replay', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_sync_replay'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-SYNC-STREAM — defined spec/31-app/06-endpoints/14-concurrency-and-sync.md:22
        register_rest_route(self::NAMESPACE, 'sync/stream', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_sync_stream'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TEMPLATES-APPLY — defined spec/31-app/06-endpoints/13-templates.md:52
        register_rest_route(self::NAMESPACE, 'templates/(?P<id>[\\w-]+)/apply', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_templates_apply'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TEMPLATES-CREATE — defined spec/31-app/06-endpoints/13-templates.md:32
        register_rest_route(self::NAMESPACE, 'templates', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_templates_create'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TEMPLATES-DELETE — defined spec/31-app/06-endpoints/13-templates.md:63
        register_rest_route(self::NAMESPACE, 'templates/(?P<id>[\\w-]+)', [
            'methods'             => 'DELETE',
            'callback'            => [self::class, 'handle_templates_delete'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TEMPLATES-GET — defined spec/31-app/06-endpoints/13-templates.md:43
        register_rest_route(self::NAMESPACE, 'templates/(?P<id>[\\w-]+)', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_templates_get'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TEMPLATES-LIST — defined spec/31-app/06-endpoints/13-templates.md:22
        register_rest_route(self::NAMESPACE, 'templates', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_templates_list'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TRASH-LIST — defined spec/31-app/06-endpoints/11-trash-view.md:21
        register_rest_route(self::NAMESPACE, 'trash', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_trash_list'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TRASH-PURGE-ALL — defined spec/31-app/06-endpoints/11-trash-view.md:52
        register_rest_route(self::NAMESPACE, 'trash', [
            'methods'             => 'DELETE',
            'callback'            => [self::class, 'handle_trash_purge_all'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TRASH-PURGE-ONE — defined spec/31-app/06-endpoints/11-trash-view.md:43
        register_rest_route(self::NAMESPACE, 'trash/(?P<id>[\\w-]+)', [
            'methods'             => 'DELETE',
            'callback'            => [self::class, 'handle_trash_purge_one'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-TRASH-RESTORE — defined spec/31-app/06-endpoints/11-trash-view.md:32
        register_rest_route(self::NAMESPACE, 'trash/(?P<id>[\\w-]+)/restore', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handle_trash_restore'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
        // EP-VIEWS-TODAY — defined spec/31-app/06-endpoints/10-today-view.md:18
        register_rest_route(self::NAMESPACE, 'views/today', [
            'methods'             => 'GET',
            'callback'            => [self::class, 'handle_views_today'],
            'permission_callback' => [self::class, 'check_permission'],
        ]);
    }

    public static function check_permission(\WP_REST_Request $request): bool {
        return is_user_logged_in();
    }

    /** TODO(EP-BOARD-GET): implement per spec/31-app/06-endpoints/07-board-view.md:19 */
    public static function handle_board_get(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-BOARD-GET'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-BOARD-MOVE): implement per spec/31-app/06-endpoints/07-board-view.md:31 */
    public static function handle_board_move(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-BOARD-MOVE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-BULK-COMPLETE): implement per spec/31-app/06-endpoints/12-multi-select.md:45 */
    public static function handle_bulk_complete(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-BULK-COMPLETE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-BULK-DELETE): implement per spec/31-app/06-endpoints/12-multi-select.md:35 */
    public static function handle_bulk_delete(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-BULK-DELETE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-BULK-MOVE): implement per spec/31-app/06-endpoints/12-multi-select.md:24 */
    public static function handle_bulk_move(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-BULK-MOVE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-BULK-TAGS): implement per spec/31-app/06-endpoints/12-multi-select.md:55 */
    public static function handle_bulk_tags(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-BULK-TAGS'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-COMPLETE): implement per spec/31-app/06-endpoints/06-item-context-menu.md:34 */
    public static function handle_items_complete(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-COMPLETE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-CREATE): implement per spec/31-app/06-endpoints/01-information-model.md:48 */
    public static function handle_items_create(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-CREATE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-DELETE): implement per spec/31-app/06-endpoints/01-information-model.md:90 */
    public static function handle_items_delete(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-DELETE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-DUPLICATE): implement per spec/31-app/06-endpoints/06-item-context-menu.md:21 */
    public static function handle_items_duplicate(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-DUPLICATE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-GET): implement per spec/31-app/06-endpoints/01-information-model.md:36 */
    public static function handle_items_get(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-GET'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-LIST): implement per spec/31-app/06-endpoints/01-information-model.md:24 */
    public static function handle_items_list(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-LIST'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-MOVE): implement per spec/31-app/06-endpoints/01-information-model.md:75 */
    public static function handle_items_move(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-MOVE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-ROOT): implement per spec/31-app/06-endpoints/01-information-model.md:101 */
    public static function handle_items_root(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-ROOT'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-TAGS): implement per spec/31-app/06-endpoints/06-item-context-menu.md:57 */
    public static function handle_items_tags(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-TAGS'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-TURN-INTO): implement per spec/31-app/06-endpoints/06-item-context-menu.md:45 */
    public static function handle_items_turn_into(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-TURN-INTO'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ITEMS-UPDATE): implement per spec/31-app/06-endpoints/01-information-model.md:64 */
    public static function handle_items_update(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ITEMS-UPDATE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ME): implement per spec/31-app/06-endpoints/02-personas.md:18 */
    public static function handle_me(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ME'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-MIRRORS-CREATE): implement per spec/31-app/06-endpoints/09-mirrors.md:20 */
    public static function handle_mirrors_create(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-MIRRORS-CREATE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-MIRRORS-DELETE): implement per spec/31-app/06-endpoints/09-mirrors.md:41 */
    public static function handle_mirrors_delete(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-MIRRORS-DELETE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-MIRRORS-DETACH): implement per spec/31-app/06-endpoints/09b-mirror-peer-group.md:32 */
    public static function handle_mirrors_detach(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-MIRRORS-DETACH'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-MIRRORS-GROUP-GET): implement per spec/31-app/06-endpoints/09b-mirror-peer-group.md:22 */
    public static function handle_mirrors_group_get(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-MIRRORS-GROUP-GET'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-MIRRORS-LIST): implement per spec/31-app/06-endpoints/09-mirrors.md:32 */
    public static function handle_mirrors_list(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-MIRRORS-LIST'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-REAPER-RUN): implement per spec/31-app/06-endpoints/11b-trash-reaper.md:22 */
    public static function handle_reaper_run(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-REAPER-RUN'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-REAPER-RUNS-LIST): implement per spec/31-app/06-endpoints/11b-trash-reaper.md:37 */
    public static function handle_reaper_runs_list(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-REAPER-RUNS-LIST'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ROLES-ASSIGN): implement per spec/31-app/06-endpoints/15-roles-and-permissions.md:32 */
    public static function handle_roles_assign(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ROLES-ASSIGN'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ROLES-LIST): implement per spec/31-app/06-endpoints/15-roles-and-permissions.md:22 */
    public static function handle_roles_list(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ROLES-LIST'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-ROLES-REVOKE): implement per spec/31-app/06-endpoints/15-roles-and-permissions.md:42 */
    public static function handle_roles_revoke(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-ROLES-REVOKE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SEARCH-QUERY): implement per spec/31-app/06-endpoints/15b-search.md:18 */
    public static function handle_search_query(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SEARCH-QUERY'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SHARES-INVITE): implement per spec/31-app/06-endpoints/08-share-dialog.md:31 */
    public static function handle_shares_invite(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SHARES-INVITE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SHARES-LIST): implement per spec/31-app/06-endpoints/08-share-dialog.md:22 */
    public static function handle_shares_list(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SHARES-LIST'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SHARES-PUBLIC): implement per spec/31-app/06-endpoints/08-share-dialog.md:61 */
    public static function handle_shares_public(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SHARES-PUBLIC'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SHARES-REVOKE): implement per spec/31-app/06-endpoints/08-share-dialog.md:52 */
    public static function handle_shares_revoke(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SHARES-REVOKE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SHARES-UPDATE): implement per spec/31-app/06-endpoints/08-share-dialog.md:42 */
    public static function handle_shares_update(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SHARES-UPDATE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SYNC-ACK): implement per spec/31-app/06-endpoints/14-concurrency-and-sync.md:53 */
    public static function handle_sync_ack(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SYNC-ACK'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SYNC-POLL): implement per spec/31-app/06-endpoints/14-concurrency-and-sync.md:42 */
    public static function handle_sync_poll(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SYNC-POLL'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SYNC-REPLAY): implement per spec/31-app/06-endpoints/14b-sync-replay.md:19 */
    public static function handle_sync_replay(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SYNC-REPLAY'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-SYNC-STREAM): implement per spec/31-app/06-endpoints/14-concurrency-and-sync.md:22 */
    public static function handle_sync_stream(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-SYNC-STREAM'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TEMPLATES-APPLY): implement per spec/31-app/06-endpoints/13-templates.md:52 */
    public static function handle_templates_apply(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TEMPLATES-APPLY'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TEMPLATES-CREATE): implement per spec/31-app/06-endpoints/13-templates.md:32 */
    public static function handle_templates_create(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TEMPLATES-CREATE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TEMPLATES-DELETE): implement per spec/31-app/06-endpoints/13-templates.md:63 */
    public static function handle_templates_delete(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TEMPLATES-DELETE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TEMPLATES-GET): implement per spec/31-app/06-endpoints/13-templates.md:43 */
    public static function handle_templates_get(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TEMPLATES-GET'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TEMPLATES-LIST): implement per spec/31-app/06-endpoints/13-templates.md:22 */
    public static function handle_templates_list(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TEMPLATES-LIST'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TRASH-LIST): implement per spec/31-app/06-endpoints/11-trash-view.md:21 */
    public static function handle_trash_list(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TRASH-LIST'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TRASH-PURGE-ALL): implement per spec/31-app/06-endpoints/11-trash-view.md:52 */
    public static function handle_trash_purge_all(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TRASH-PURGE-ALL'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TRASH-PURGE-ONE): implement per spec/31-app/06-endpoints/11-trash-view.md:43 */
    public static function handle_trash_purge_one(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TRASH-PURGE-ONE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-TRASH-RESTORE): implement per spec/31-app/06-endpoints/11-trash-view.md:32 */
    public static function handle_trash_restore(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-TRASH-RESTORE'],
            'Results'    => null,
        ], 501);
    }

    /** TODO(EP-VIEWS-TODAY): implement per spec/31-app/06-endpoints/10-today-view.md:18 */
    public static function handle_views_today(\WP_REST_Request $request): \WP_REST_Response {
        return new \WP_REST_Response([
            'Status'     => ['Code' => 501, 'Message' => 'NotImplemented'],
            'Attributes' => ['EndpointId' => 'EP-VIEWS-TODAY'],
            'Results'    => null,
        ], 501);
    }

}